// <auto-generated />
using System;
using Infrastructure_Layer.MyContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure_Layer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain_Layer.Domains.Applicant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CoverPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MJR_ID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Message2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UNV_ID")
                        .HasColumnType("int");

                    b.Property<int?>("workplace")
                        .HasColumnType("int");

                    b.Property<int?>("yearsofexperience")
                        .HasColumnType("int");

                    b.Property<int?>("yearsofexperience2")
                        .HasColumnType("int");

                    b.Property<int?>("yearsofexperience3")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MJR_ID");

                    b.HasIndex("UNV_ID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Domain_Layer.Domains.Major", b =>
                {
                    b.Property<int>("MJR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MJR_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MJR_ID");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("Domain_Layer.Domains.University", b =>
                {
                    b.Property<int>("UNV_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UNV_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UNV_ID");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Domain_Layer.Domains.Applicant", b =>
                {
                    b.HasOne("Domain_Layer.Domains.Major", "major")
                        .WithMany("Applicants")
                        .HasForeignKey("MJR_ID");

                    b.HasOne("Domain_Layer.Domains.University", "university")
                        .WithMany("Applicants")
                        .HasForeignKey("UNV_ID");

                    b.Navigation("major");

                    b.Navigation("university");
                });

            modelBuilder.Entity("Domain_Layer.Domains.Major", b =>
                {
                    b.Navigation("Applicants");
                });

            modelBuilder.Entity("Domain_Layer.Domains.University", b =>
                {
                    b.Navigation("Applicants");
                });
#pragma warning restore 612, 618
        }
    }
}
